"""
MUST ADD GOOGLE SHEEETS API AND THE DRAFT ORDER INITALIZATION CODE IN THE BEGINNING FOR THIS TO RUN, THIS WILL FILL OUT THE GOOGLE SHEETS SECTION THAT IS THE DATABASE FOR WHEN THE BOT RESTARTS
"""

tempdraft = [[pick] for pick in draft]
sheet.sheet1.update("T3:T170", tempdraft)
